# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

def set_hostname(server)
  server.vm.provision 'shell', inline: "hostname #{server.vm.hostname}"
end

Vagrant.configure(2) do |config|
  config.ssh.private_key_path = "C:/Users/vishnuch/.vagrant.d/insecure_private_key"
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  #HA Proxy
  config.vm.define 'node-haproxy' do |m|
    m.vm.box = 'bento/centos-7.2'
    m.vm.hostname = 'haproxy'
    m.vm.network 'private_network', ip: '10.1.1.30'
    m.vm.network :forwarded_port, guest: 80, host: 8082
    m.vm.network :forwarded_port, guest: 22, host: 2222
    set_hostname(m)
  end
  #HTTP Server
  config.vm.define 'node-web-server' do |n|
    n.vm.box = 'bento/centos-7.2'
    n.vm.hostname = 'web-server'
    n.vm.network 'private_network', ip: '10.1.1.31'
    n.vm.network :forwarded_port, guest: 80, host: 8084
    n.vm.network :forwarded_port, guest: 22, host: 2224
    set_hostname(n)
  end
  #Application Server
  config.vm.define 'node-app-server' do |o|
    o.vm.box = 'bento/centos-7.2'
    o.vm.hostname = 'app-server'
    o.vm.network 'private_network', ip: '10.1.1.32'
    o.vm.network :forwarded_port, guest: 80, host: 8086
    o.vm.network :forwarded_port, guest: 22, host: 2226
    set_hostname(o)
  end
  #DB Server
  config.vm.define 'node-db-server' do |p|
    p.vm.box = 'bento/centos-7.2'
    p.vm.hostname = 'db-server'
    p.vm.network 'private_network', ip: '10.1.1.33'
    p.vm.network :forwarded_port, guest: 80, host: 8088
    p.vm.network :forwarded_port, guest: 22, host: 2228
    set_hostname(p)
  end
end
