#
# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

def set_hostname(server)
  server.vm.provision 'shell', inline: "hostname #{server.vm.hostname}"
end


Vagrant.configure(2) do |config1|
  config1.ssh.private_key_path = "C:/Users/vishnuch/.vagrant.d/insecure_private_key"
  config1.ssh.forward_agent = true
  config1.ssh.insert_key = false
  config1.ssh.username = "vagrant"
  config1.ssh.password = "vagrant"
  config1.vm.provider 'virtualbox' do |v|
  	v.memory = 1024
  	v.cpus = 2
  end
  #chef Server
  config1.vm.define 'node-chef-server' do |r|
    r.vm.box = 'bento/ubuntu-14.04'
    r.vm.hostname = 'chef-server'
    r.vm.network 'private_network', ip: '10.1.1.35'
    r.vm.network :forwarded_port, guest: 80, host: 8092
    r.vm.network :forwarded_port, guest: 22, host: 2232
    r.vm.network :forwarded_port, guest: 443, host: 4431
    r.vm.provision :shell, inline: CHEF_SERVER_SCRIPT.dup
    set_hostname(r)
  end

CHEF_SERVER_SCRIPT = <<EOF.freeze
apt-get update
apt-get -y install curl

# ensure the time is up to date
echo "Synchronizing time..."
apt-get -y install ntp
service ntp stop
ntpdate -s time.nist.gov
service ntp start

# download the Chef server package
echo "Downloading the Chef server package..."
if [ ! -f /downloads/chef-server-core_12.11.1_amd64.deb ]; then
  wget -nv -P /downloads https://packages.chef.io/files/stable/chef-server/12.11.1/ubuntu/14.04/chef-server-core_12.11.1-1_amd64.deb
fi

# install the package
echo "Installing Chef server..."
sudo dpkg -i /downloads/chef-server-core_12.11.1-1_amd64.deb

# reconfigure and restart services
echo "Reconfiguring Chef server..."
sudo chef-server-ctl reconfigure
echo "Restarting Chef server..."
sudo chef-server-ctl restart

# wait for services to be fully available
echo "Waiting for services..."
until (curl -D - http://localhost:8000/_status) | grep "200 OK"; do sleep 15s; done
while (curl http://localhost:8000/_status) | grep "fail"; do sleep 15s; done

# create admin user
echo "Creating a user and organization..."
sudo chef-server-ctl user-create admin Govind Rajan admin@govind.com insecurepassword --filename admin.pem
sudo chef-server-ctl org-create 4thcoffee "Fourth Coffee, Inc." --association_user admin --filename 4thcoffee-validator.pem

# copy admin RSA private key to share
echo "Copying admin key to /vagrant/secrets..."
mkdir -p /vagrant/secrets
cp -f /home/vagrant/admin.pem /vagrant/secrets

echo "Your Chef server is ready!"
EOF

end 
