# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :


NODE_SCRIPT = <<EOF.freeze
echo "Preparing node..."

# ensure the time is up to date
yum -y install ntp
systemctl start ntpd
systemctl enable ntpd
EOF

def set_hostname(server)
  server.vm.provision 'shell', inline: "hostname #{server.vm.hostname}"
end

Vagrant.configure(2) do |config|
  config.ssh.private_key_path = "C:/Users/vishnuch/.vagrant.d/insecure_private_key"
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.define 'node2-centos' do |m|
    m.vm.box = 'bento/centos-7.2'
    m.vm.hostname = 'node2-centos'
    m.vm.network 'private_network', ip: '192.100.100.100'
    m.vm.provision :shell, inline: NODE_SCRIPT.dup
    m.vm.network :forwarded_port, guest: 80, host: 8082
    set_hostname(m)
  end
  config.vm.define 'node1-centos' do |n|
    n.vm.box = 'bento/centos-7.2'
    n.vm.hostname = 'node1-centos'
    n.vm.network 'private_network', ip: '192.100.100.101'
    n.vm.provision :shell, inline: NODE_SCRIPT.dup
    n.vm.network :forwarded_port, guest: 80, host: 8084
    set_hostname(n)
  end
end
